### ISSUE TITLE
usermod stuck in loop when running on mac

### ISSUE THREAD

**Issue by madpsy** [snw35/cloudenv#1]
When running on a mac, usermod chews CPU and never exits.

Suspect issue caused by large UID (327472772)

**Comment by snw35** [comment]
Looks like a known bug:
https://github.com/moby/moby/issues/5419
https://github.com/containers/libpod/issues/1808

It seems you have to avoid anything that touches /var/log/lastlog when you have a UID or GID over ~8 digits, so 'usermod' isn't an option. 

Deleting and re-creating the user, or resorting to sed may be the way forward...

**Comment by snw35** [comment]
Resolved by switching to useradd and groupadd instead
