### ISSUE TITLE
add gnumake

### ISSUE THREAD

**Issue by shadow431** [snw35/cloudenv#11]
Would it be possible to add gnu make?

**Comment by snw35** [comment]
Hi, my first thought is that make is more of a build-time package, rather than a run-time one (e.g used to set the image up and build/install tools, the removed to save on space). Are you wanting to use it to install further packages into the image?

**Comment by shadow431** [comment]
I've started to use MakeFiles for my various processes for terraform/terragrunt.  mainly to reduce manual vs pipeline variances. so for instance i have a makefile that does my hclfmt input validation tg init plans and applys templated allowing me to run per env or per module in the env.   

so i just run for example

make dev.validate and it will run a swath of validations against all the tg/tf code or i can run make dev.validate.format.hcl parser_lambda and it will hcl format check just the one module.  but its always the same arguments and steps

**Comment by snw35** [comment]
Apologies for the wait - I've had to switch to a different base image due to AWS CLI incompatibilities with alpine and have also had to make numerous other fixes to get the automated updates back on track. I've added `make` now so you should find it pre-installed in future versions.
