### ISSUE TITLE
Vulnerabilities in the docker container

### ISSUE THREAD

**Issue by viebrock** [snw35/cloudenv#4]
Hi,
I just ran a snyk test against that latest version of the container, and it reported a couple vulns.  I'm fairly certain the musl vulnerability is a false-positive, but might want to update the jq package to address.

Thanks.

-Dave

dviebrock@FVFX62JZHV2D gitlab-eks-cluster % snyk container test snw35/cloudenv:latest 
Testing snw35/cloudenv:latest...
✗ Medium severity vulnerability found in musl/musl-utils
  Description: Out-of-bounds Write
  Info: https://snyk.io/vuln/SNYK-ALPINE313-MUSL-1067865
  Introduced through: musl/musl-utils@1.2.2-r0, libc-dev/libc-utils@0.7.2-r3, meta-common-packages@meta
  From: musl/musl-utils@1.2.2-r0
  From: libc-dev/libc-utils@0.7.2-r3 > musl/musl-utils@1.2.2-r0
  From: meta-common-packages@meta > musl/musl@1.2.2-r0
  Fixed in: 1.2.2_pre2-r0
✗ High severity vulnerability found in jq/jq
  Description: Out-of-Bounds
  Info: https://snyk.io/vuln/SNYK-ALPINE313-JQ-1067448
  Introduced through: jq/jq@1.6-r1
  From: jq/jq@1.6-r1
  Image layer: '/bin/sh -c apk --update --no-cache upgrade -a   && apk --update --no-cache add     bash     bash-completion     bind-tools     ca-certificates     coreutils     curl     diffutils     fish     fzf     fzf-bash-completion     git     gnupg     groff     iputils     jq     keychain     libusb     ncurses     net-tools     nmap     openssh-client     openssl     perl     py3-pip     python3     shadow     su-exec     tmux     tzdata   && pip install --upgrade pip   && pip install --no-cache-dir      cookiecutter     datadog     okta-awscli     wheel   && curl -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest   && chmod +x /usr/local/bin/ecs-cli   && sed -i 's/^CREATE_MAIL_SPOOL=yes/CREATE_MAIL_SPOOL=no/' /etc/default/useradd   && mkdir -p /etc/bash_completion.d   && ln -s /usr/bin/python3 /usr/bin/python'
  Fixed in: 1.6_rc1-r0
Organization:      dave.viebrock
Package manager:   apk
Project name:      docker-image|snw35/cloudenv
Docker image:      snw35/cloudenv:latest
Platform:          linux/amd64
Licenses:          enabled
Tested 141 dependencies for known issues, found 2 issues.

**Comment by snw35** [comment]
Thanks for this!

The version of jq included will be the latest available in Alpine's repos at the time of build, and looks to already be at a version that contains this fix. I'd guess this is a false-positive caused by Alpine's way of versioning the jq package.

Vulnerabilities are kept to a minimum in general by using the latest available OS and installed software packages or releases, so as long as the latest available version of the container is used, the vulnerability profile should be at the minimum possible at the time.

**Comment by snw35** [comment]
Closing as these both look like false-positives. Thanks for reporting: it's useful to know there aren't any other issues with the image. Adding vulnerability scanning on build is something I definitely want to add at some point.
