### ISSUE TITLE
Version regression??

### ISSUE THREAD

**Issue by shadow431** [snw35/cloudenv#5]
https://github.com/snw35/cloudenv/blob/c84825798fc2b88d890dd2d805231e40997c79d5/Dockerfile#L144

Looks like we went from terraform 0.15.0 -> 0.11.15???

this commit here?
https://github.com/snw35/cloudenv/commit/c84825798fc2b88d890dd2d805231e40997c79d5

**Comment by snw35** [comment]
Yes, the upstream release repo for terraform posted 0.11.15 as the latest tag, which is a condition that hasn't come up before. I've switched to using "max tag" instead, which should hopefully detect the correct thing for latest in future, barring them changing their version format.

**Comment by snw35** [comment]
Closing as resolved, please re-open or create another issue if any more version regressions are spotted. Upstream projects can change their tagging order/strategy at any time so these situations need to just be handled when they come up.
