### ISSUE TITLE
SSH agent forwarding broken when in a multi-host-hop scenario

### ISSUE THREAD

**Issue by shyam-habarakada** [snw35/cloudenv#8]
To reproduce,

- Host (laptop) with agent forwarding enabled
- SSH to remote host
  - Test `ssh -v git@gitlab.com` and see it succeeds using keys forwarded from the laptop
  - Install cloudenv on this same remote host
  - Run cloudenv
    - Test `ssh -v git@gitlab.com` and see it fails 

Inside cloud env, `SSH_AUTH_SOCK` is not mounted and pointing to the host sock as expected.

**Comment by snw35** [comment]
Thanks for this, I'll take a look and see what removing the check for `$SSH_AGENT_PID` will do on systems where it is set. I remember settling on the two checks as there were cases where an SSH agent was installed, but not running. Supporting remote use may need the agent to always start with the host socket bound, in which case that should be fine if doesn't cause any issues with direct use on the remote host itself.

**Comment by shyam-habarakada** [comment]
That would be great. In the wrapper, I can't see us passing in anything about the PID so it looks safe to remove, but another pair of eyes (and more context for why that check was there) is prudent before this can be merged.

**Comment by snw35** [comment]
Merged the PR, thanks again!
